{TCP,UART}CtrlIntfModule.cpp: fix compilation error
The error is the following:
'error: designated initializers cannot be used with a non-aggregate
type'

The error when ARM GNU Toolchain was updated from 9-2020-q2-update to
13.3.Rel1 (July 04, 2024). I don't know exactly why. However, the fix is
simple: use struct constructors instead of designated initializers.